name: CI

on:
  pull_request:
    branches: [main]

jobs:
  checks:
    name: Type-check & Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci
      - name: Type-check
        run: npm run type-check
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run ci:test
